kind: Pod
apiVersion: v1
metadata:
  name: pod3
  labels:
    group: ckastudents
  namespace: dev  
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443


