kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment1
spec:
  replicas: 10
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
        - name: cont1
          image: lerndevops/samplepyapp:v1
          ports:
            - name: http
              containerPort: 3000
