kind: Pod
apiVersion: v1
metadata:
  name: podcreater
  labels:
    group: ckastudents
    namespace: dev
spec:
  initContainers:
    - name: initcont1
      image: ubuntu
      command: ["sh","-c","sleep 60"]
  containers: 
    - name: cont1
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
    - name: cont2
      image: tomcat
      ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
