kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: rs1
  #labels:

spec:
  replicas: 4
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      #name: test
      labels:
        role: app
    spec:
      containers:
        - name: cont1
          image: lerndevops/samplepyapp:v1
          ports:
            - name: http
              containerPort: 3000

